"""Render the audit report.

Deterministic. No model is consulted here.

Three outputs are produced from one set of results:

  report.md   the full record, including every process map and every rationale
  report.html the one page summary, styled for print
  report.pdf  the same one page summary through WeasyPrint

The PDF is the only output with an external system dependency. WeasyPrint needs the
Pango and GObject native libraries, which are not present on every machine. When
they are missing, the markdown and HTML are still written and the caller is told
plainly what happened, because a missing PDF should not lose the analysis.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined, select_autoescape

from ..processmap.mermaid import render_mermaid
from ..scoring.score import AuditResult

TEMPLATE_DIR = Path(__file__).with_name("templates")

# Printed on every report, in every format. The wording is deliberately plain and
# deliberately not buried at the bottom in small type.
DISCLOSURE = (
    "This report was generated by an AI system. It scores each process against a "
    "fixed rubric of six criteria and ranks the results. It has not visited the "
    "business, spoken to anyone, or checked any of the figures it was given. Treat "
    "every finding as a starting point for a human review, not as a decision."
)

# How many rows the one page summary can hold before it stops being one page.
SUMMARY_ROW_LIMIT = 8


class PdfUnavailableError(RuntimeError):
    """Raised when WeasyPrint cannot run on this machine."""


@dataclass(frozen=True)
class ReportPaths:
    """Where each output landed. pdf is None when WeasyPrint could not run."""

    markdown: Path
    html: Path
    pdf: Path | None
    mermaid: tuple[Path, ...] = ()
    pdf_error: str | None = None


def _format_number(value: float) -> str:
    return f"{int(round(value)):,}"


def _format_score(value: float) -> str:
    return f"{value:.2f}"


def _environment() -> Environment:
    env = Environment(
        loader=FileSystemLoader(TEMPLATE_DIR),
        # Autoescape is matched on the full suffix, so report.html.j2 is escaped and
        # report.md.j2 is not.
        autoescape=select_autoescape(
            enabled_extensions=("html", "htm", "html.j2"), default=False
        ),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    env.filters["number"] = _format_number
    env.filters["score"] = _format_score
    return env


def _context(result: AuditResult, generated_on: date | None) -> dict:
    generated_on = generated_on or date.today()
    shown = result.opportunities[:SUMMARY_ROW_LIMIT]
    warnings: list[str] = []
    if result.judge_mode == "stub":
        warnings.append(
            "Scores in this report came from the stub judge, which applies fixed "
            "thresholds to the intake rather than making a judgement. They show that "
            "the pipeline runs. They are not an assessment."
        )
    if not result.rubric_is_approved:
        warnings.append(
            f"Rubric {result.rubric.version} is a draft and has not been approved, so "
            "the weights behind these rankings are still open to change."
        )
    assumed = [
        opportunity.process.name
        for opportunity in result.opportunities
        if opportunity.process.frequency_is_assumed
    ]
    if assumed:
        warnings.append(
            "Frequency was given as ad hoc for "
            + ", ".join(assumed)
            + ", so monthly was assumed for scoring."
        )

    return {
        "result": result,
        "intake": result.intake,
        "business": result.intake.business,
        "opportunities": result.opportunities,
        "summary_rows": shown,
        "hidden_row_count": max(0, len(result.opportunities) - len(shown)),
        "rubric": result.rubric,
        "generated_on": generated_on.isoformat(),
        "disclosure": DISCLOSURE,
        "warnings": warnings,
        "render_mermaid": render_mermaid,
    }


def render_markdown(result: AuditResult, generated_on: date | None = None) -> str:
    """Render the full markdown report."""
    template = _environment().get_template("report.md.j2")
    return template.render(**_context(result, generated_on))


def render_html(result: AuditResult, generated_on: date | None = None) -> str:
    """Render the one page HTML summary."""
    template = _environment().get_template("report.html.j2")
    return template.render(**_context(result, generated_on))


def render_pdf(html: str, destination: Path, base_url: Path | None = None) -> Path:
    """Write the HTML to a PDF.

    Raises PdfUnavailableError when WeasyPrint cannot load its native libraries,
    which is the usual failure on Windows without the GTK runtime and on any ARM64
    Windows machine, where that runtime is not available at all.
    """
    try:
        from weasyprint import HTML  # imported lazily so the rest of the tool still runs
    except Exception as exc:
        raise PdfUnavailableError(
            "WeasyPrint could not load its native libraries, so no PDF was written. "
            "The markdown and HTML reports were still produced, and the HTML can be "
            "printed to PDF from any browser. Underlying error: "
            f"{type(exc).__name__}: {exc}"
        ) from exc

    destination.parent.mkdir(parents=True, exist_ok=True)
    HTML(string=html, base_url=str(base_url or TEMPLATE_DIR)).write_pdf(str(destination))
    return destination


def write_reports(
    result: AuditResult,
    output_dir: str | Path,
    generated_on: date | None = None,
    write_mermaid_files: bool = True,
) -> ReportPaths:
    """Render every output into output_dir.

    Never raises when the PDF cannot be produced. The failure is reported on the
    returned object so the caller can decide how loud to be about it.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    markdown_path = output_dir / "report.md"
    html_path = output_dir / "report.html"
    markdown_path.write_text(render_markdown(result, generated_on), encoding="utf-8")
    html = render_html(result, generated_on)
    html_path.write_text(html, encoding="utf-8")

    mermaid_paths: list[Path] = []
    if write_mermaid_files:
        maps_dir = output_dir / "maps"
        maps_dir.mkdir(exist_ok=True)
        for opportunity in result.opportunities:
            path = maps_dir / f"{opportunity.process.id}.mmd"
            path.write_text(render_mermaid(opportunity.process_map), encoding="utf-8")
            mermaid_paths.append(path)

    pdf_path: Path | None = None
    pdf_error: str | None = None
    try:
        pdf_path = render_pdf(html, output_dir / "report.pdf")
    except PdfUnavailableError as exc:
        pdf_error = str(exc)

    return ReportPaths(
        markdown=markdown_path,
        html=html_path,
        pdf=pdf_path,
        mermaid=tuple(mermaid_paths),
        pdf_error=pdf_error,
    )
