"""Render the audit report.

Deterministic. No model is consulted here.

Three outputs are produced from one set of results:

  report.md   the full record, including every process map and every rationale
  report.html the one page summary, styled for print
  report.pdf  the same one page summary

The PDF is the only output with an external system dependency, so there are two ways
to produce it and both are optional:

  1. WeasyPrint, which is the intended renderer. It needs the Pango and GObject
     native libraries. On Windows that means the GTK runtime, and on Windows ARM64
     that runtime does not exist, so WeasyPrint cannot render there at all.
  2. Microsoft Edge in headless mode, which every Windows machine already has. It is
     tried only when WeasyPrint is unavailable, and it adds no dependency because it
     is a program that is already installed rather than a package.

If neither works, the markdown and HTML are still written and the caller is told
plainly what happened, because a missing PDF should not lose the analysis. The two
renderers do not produce identical files: Edge does not support the CSS that puts a
running footer on the page, so the Edge PDF has no page footer. Everything the
footer carries also appears in the body, so nothing is lost.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined, select_autoescape

from ..processmap.mermaid import render_mermaid
from ..scoring.score import AuditResult

TEMPLATE_DIR = Path(__file__).with_name("templates")

# Printed on every report, in every format. The wording is deliberately plain and
# deliberately not buried at the bottom in small type.
DISCLOSURE = (
    "This report was generated by an AI system. It scores each process against a "
    "fixed rubric of six criteria and ranks the results. It has not visited the "
    "business, spoken to anyone, or checked any of the figures it was given. Treat "
    "every finding as a starting point for a human review, not as a decision."
)

# How many rows the one page summary can hold before it stops being one page.
SUMMARY_ROW_LIMIT = 8


# Where Edge usually lives on Windows. Set AI_PROCESS_AUDIT_EDGE to point at a
# specific Chromium binary instead, which is also how to use Chrome rather than Edge.
EDGE_ENV_VAR = "AI_PROCESS_AUDIT_EDGE"
EDGE_CANDIDATES = (
    r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
)

EDGE_TIMEOUT_SECONDS = 120

# Edge can exit before the PDF has finished being written, so the process returning
# is not the same as the file existing. It is worse when Edge is already running,
# because the command hands work to another process and the one we launched returns
# almost immediately. Without this wait the renderer looks broken on exactly the
# machines where somebody has a browser open, which is most of them.
EDGE_WRITE_TIMEOUT_SECONDS = 30
EDGE_POLL_SECONDS = 0.25


class PdfUnavailableError(RuntimeError):
    """Raised when no renderer on this machine could produce the PDF."""


@dataclass(frozen=True)
class ReportPaths:
    """Where each output landed. pdf is None when no renderer could produce one."""

    markdown: Path
    html: Path
    pdf: Path | None
    mermaid: tuple[Path, ...] = ()
    pdf_error: str | None = None
    pdf_renderer: str | None = None


def _format_number(value: float) -> str:
    return f"{int(round(value)):,}"


def _format_score(value: float) -> str:
    return f"{value:.2f}"


def _environment() -> Environment:
    env = Environment(
        loader=FileSystemLoader(TEMPLATE_DIR),
        # Autoescape is matched on the full suffix, so report.html.j2 is escaped and
        # report.md.j2 is not.
        autoescape=select_autoescape(
            enabled_extensions=("html", "htm", "html.j2"), default=False
        ),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    env.filters["number"] = _format_number
    env.filters["score"] = _format_score
    return env


def _context(result: AuditResult, generated_on: date | None) -> dict:
    generated_on = generated_on or date.today()
    shown = result.opportunities[:SUMMARY_ROW_LIMIT]
    warnings: list[str] = []
    if result.judge_mode == "stub":
        warnings.append(
            "Scores in this report came from the stub judge, which applies fixed "
            "thresholds to the intake rather than making a judgement. They show that "
            "the pipeline runs. They are not an assessment."
        )
    if not result.rubric_is_approved:
        warnings.append(
            f"Rubric {result.rubric.version} is a draft and has not been approved, so "
            "the weights behind these rankings are still open to change."
        )
    no_baseline = [
        opportunity.process.name
        for opportunity in result.opportunities
        if not opportunity.process.has_baseline
    ]
    if no_baseline:
        warnings.append(
            "No number is tracked today for "
            + ", ".join(no_baseline)
            + ", so the return on those cannot be evidenced and their return band is "
            "capped. The first piece of work on any of them is to start counting."
        )
    capped = [
        opportunity.process.name
        for opportunity in result.opportunities
        if opportunity.was_capped
    ]
    if capped:
        warnings.append(
            "The recommendation for "
            + ", ".join(capped)
            + " was capped below what the score earned, because a mistake there would "
            "be a serious event. The score is reported as calculated."
        )
    assumed = [
        opportunity.process.name
        for opportunity in result.opportunities
        if opportunity.process.frequency_is_assumed
    ]
    if assumed:
        warnings.append(
            "Frequency was given as ad hoc for "
            + ", ".join(assumed)
            + ", so monthly was assumed for scoring."
        )

    # Processes the business already plans to change the system under. Reported as a
    # sequencing note and nothing more. No score, cap, or band is affected by it, and
    # no recommendation is derived from it yet.
    planned_changes = [
        opportunity
        for opportunity in result.opportunities
        if opportunity.process.planned_system_change is not None
    ]

    return {
        "result": result,
        "intake": result.intake,
        "planned_changes": planned_changes,
        "business": result.intake.business,
        "opportunities": result.opportunities,
        "summary_rows": shown,
        "hidden_row_count": max(0, len(result.opportunities) - len(shown)),
        "rubric": result.rubric,
        "generated_on": generated_on.isoformat(),
        "disclosure": DISCLOSURE,
        "warnings": warnings,
        "render_mermaid": render_mermaid,
    }


def render_markdown(result: AuditResult, generated_on: date | None = None) -> str:
    """Render the full markdown report."""
    template = _environment().get_template("report.md.j2")
    return template.render(**_context(result, generated_on))


def render_html(result: AuditResult, generated_on: date | None = None) -> str:
    """Render the one page HTML summary."""
    template = _environment().get_template("report.html.j2")
    return template.render(**_context(result, generated_on))


def render_pdf(html: str, destination: Path, base_url: Path | None = None) -> Path:
    """Write the HTML to a PDF.

    Raises PdfUnavailableError when WeasyPrint cannot load its native libraries,
    which is the usual failure on Windows without the GTK runtime and on any ARM64
    Windows machine, where that runtime is not available at all.
    """
    try:
        from weasyprint import HTML  # imported lazily so the rest of the tool still runs
    except Exception as exc:
        raise PdfUnavailableError(
            "WeasyPrint could not load its native libraries, so no PDF was written. "
            "The markdown and HTML reports were still produced, and the HTML can be "
            "printed to PDF from any browser. Underlying error: "
            f"{type(exc).__name__}: {exc}"
        ) from exc

    destination.parent.mkdir(parents=True, exist_ok=True)
    HTML(string=html, base_url=str(base_url or TEMPLATE_DIR)).write_pdf(str(destination))
    return destination


def find_edge() -> Path | None:
    """Locate a Chromium binary that can print to PDF, or return None."""
    override = os.environ.get(EDGE_ENV_VAR)
    if override:
        path = Path(override)
        return path if path.exists() else None
    on_path = shutil.which("msedge")
    if on_path:
        return Path(on_path)
    for candidate in EDGE_CANDIDATES:
        if Path(candidate).exists():
            return Path(candidate)
    return None


def _wait_for_pdf(destination: Path) -> bool:
    """Wait for the PDF to appear and stop growing.

    Returns False if nothing usable arrived in time. Size is checked as well as
    existence, because a file that exists at zero bytes is a write in progress, and a
    stable size across two polls is the cheapest way to tell a finished write from a
    partial one without parsing the file.
    """
    deadline = time.monotonic() + EDGE_WRITE_TIMEOUT_SECONDS
    last_size = -1
    while time.monotonic() < deadline:
        size = _size_or_none(destination)
        if size is not None and size > 0 and size == last_size:
            return True
        last_size = size if size is not None else -1
        time.sleep(EDGE_POLL_SECONDS)
    final = _size_or_none(destination)
    return final is not None and final > 0


def _size_or_none(path: Path) -> int | None:
    """Size of a file, or None if it is not there or cannot be read yet."""
    try:
        return path.stat().st_size
    except OSError:
        # Missing, or briefly locked by the writer. Both mean not ready.
        return None


def render_pdf_with_edge(html_path: Path, destination: Path) -> Path:
    """Print an HTML file to PDF using headless Edge.

    This is the fallback for machines where WeasyPrint cannot load its libraries. It
    shells out to a browser that is already installed rather than adding a package.
    """
    edge = find_edge()
    if edge is None:
        raise PdfUnavailableError(
            "Microsoft Edge was not found, so the fallback PDF renderer could not run "
            f"either. Set {EDGE_ENV_VAR} to the full path of msedge.exe or another "
            "Chromium browser if it is installed somewhere unusual."
        )

    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        # Edge appends nothing and reports success even when it wrote nothing, so an
        # old file left in place would look like a fresh render.
        destination.unlink()

    # Edge resolves a relative output path against its own working directory, not
    # ours, and then reports success after failing to write. Give it an absolute one.
    destination = destination.resolve()
    source_url = html_path.resolve().as_uri()

    # The profile directory is made and removed by hand rather than with a context
    # manager. Edge exits before it has finished with the directory, so an automatic
    # cleanup raises PermissionError on Windows while the files are still held open,
    # and a failed cleanup of a throwaway profile should never fail a report.
    profile_dir = tempfile.mkdtemp(prefix="ai-process-audit-edge-")
    try:
        command = [
            str(edge),
            "--headless",
            "--disable-gpu",
            "--no-pdf-header-footer",
            # A throwaway profile, so this cannot disturb a running Edge session.
            f"--user-data-dir={profile_dir}",
            # A brand new profile otherwise triggers the first run and sync flows,
            # and Edge exits zero without ever printing. These four are what make the
            # throwaway profile usable rather than a silent failure.
            "--no-first-run",
            "--no-default-browser-check",
            "--disable-sync",
            "--disable-extensions",
            f"--print-to-pdf={destination}",
            source_url,
        ]
        try:
            completed = subprocess.run(
                command,
                capture_output=True,
                text=True,
                timeout=EDGE_TIMEOUT_SECONDS,
                check=False,
            )
        except subprocess.TimeoutExpired:
            raise PdfUnavailableError(
                f"Edge did not finish printing within {EDGE_TIMEOUT_SECONDS} seconds, "
                "so no PDF was written."
            ) from None
        except OSError as exc:
            raise PdfUnavailableError(f"Edge could not be started: {exc}") from exc

        if not _wait_for_pdf(destination):
            detail = (completed.stderr or completed.stdout or "").strip().splitlines()
            last_line = detail[-1] if detail else "no output"
            raise PdfUnavailableError(
                f"Edge ran but wrote no PDF within {EDGE_WRITE_TIMEOUT_SECONDS} seconds "
                f"(exit code {completed.returncode}). Last thing it said: {last_line}"
            )
        return destination
    finally:
        shutil.rmtree(profile_dir, ignore_errors=True)


def write_reports(
    result: AuditResult,
    output_dir: str | Path,
    generated_on: date | None = None,
    write_mermaid_files: bool = True,
) -> ReportPaths:
    """Render every output into output_dir.

    Never raises when the PDF cannot be produced. The failure is reported on the
    returned object so the caller can decide how loud to be about it.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    markdown_path = output_dir / "report.md"
    html_path = output_dir / "report.html"
    markdown_path.write_text(render_markdown(result, generated_on), encoding="utf-8")
    html = render_html(result, generated_on)
    html_path.write_text(html, encoding="utf-8")

    mermaid_paths: list[Path] = []
    if write_mermaid_files:
        maps_dir = output_dir / "maps"
        maps_dir.mkdir(exist_ok=True)
        for opportunity in result.opportunities:
            path = maps_dir / f"{opportunity.process.id}.mmd"
            path.write_text(render_mermaid(opportunity.process_map), encoding="utf-8")
            mermaid_paths.append(path)

    pdf_path: Path | None = None
    pdf_renderer: str | None = None
    failures: list[str] = []
    try:
        pdf_path = render_pdf(html, output_dir / "report.pdf")
        pdf_renderer = "weasyprint"
    except PdfUnavailableError as exc:
        failures.append(str(exc))
        try:
            pdf_path = render_pdf_with_edge(html_path, output_dir / "report.pdf")
            pdf_renderer = "edge"
        except PdfUnavailableError as fallback_exc:
            failures.append(str(fallback_exc))

    return ReportPaths(
        markdown=markdown_path,
        html=html_path,
        pdf=pdf_path,
        mermaid=tuple(mermaid_paths),
        pdf_error=None if pdf_path is not None else " ".join(failures),
        pdf_renderer=pdf_renderer,
    )
